# Top of file
version: 2
jobs: # 'jobs' is a parent-level dictionary of YAML and each mapping underneath is a job
  build: # CircleCI automatically expects a job called 'build'
    docker:
      - image: circleci/ruby:2.4.2-jessie-node # Image that runs on Debian Jessie and installs both Ruby 2.4.2 and Node.js
        environment: # Environment variables for primary container
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
  working_directory: ~/repo
  steps: # A collection of executable commands
    - add_ssh_keys:
        fingerprints:
    - checkout # Checks out the source code

    # Restore bundle cache
    # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
    - restore_cache:
        keys:
          - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
          - rails-demo-bundle-v2-

    - run: # Install Ruby dependencies
        name: Bundle Install
        command: bundle check --path vendor/bundle || bundle install --deployment

      # Store bundle cache for Ruby dependencies
    - save_cache:
        key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

    - run: wget https://github.com/jgm/pandoc/releases/download/1.19.1/pandoc-1.19.1-1-amd64.deb # Getting and downloading file
    - run: sudo dpkg -i pandoc-1.19.1-1-amd64.deb
    - run: bundle exec ruby render.rb
    - save_cache:
        key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
        paths:
          - "."
  deploy:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - add_ssh_keys:
          fingerprints:
            - 
      - run:
          name: Deployment script
          command: ./deploy.sh
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: develop